"""empty message

Revision ID: 756be700b00e
Revises: acb490713df4
Create Date: 2022-05-11 19:44:29.935747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756be700b00e'
down_revision = 'acb490713df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True, default='https://capstone-profile-pics.s3.us-east-2.amazonaws.com/user.png'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
