"""empty message

Revision ID: ae2b00f9ca07
Revises: 756be700b00e
Create Date: 2022-05-18 00:20:13.685412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2b00f9ca07'
down_revision = '756be700b00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_anime_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_poster_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['poster_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'animes', ['anime_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_poster_id_fkey', 'comments', 'animes', ['poster_id'], ['id'])
    op.create_foreign_key('comments_anime_id_fkey', 'comments', 'users', ['anime_id'], ['id'])
    # ### end Alembic commands ###
